# Generated by Django 4.2.7 on 2023-11-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinventario', '0002_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
