# Generated by Django 4.2.7 on 2023-11-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinventario', '0003_rename_id_usuario_orden_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor_id',
            new_name='proveedor',
        ),
    ]
